version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: gunicorn -b 0.0.0.0:8000 -w 8 palaemon_logging_service.wsgi:application
    ports:
      - 127.0.0.1:8123:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail http://127.0.0.1:8000 || exit 1"
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      DJANGO_SETTINGS_MODULE: "palaemon_logging_service.settings.production"
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      web:
        condition: service_healthy
    ports:
      - 127.0.0.1:8080:80
    
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /opt/palaemon_logging/db:/var/lib/postgresql/data